Migration to gitHub action
commercetools/commercetools-paypal-plus-integration pull request #201
Opened 2021-09-17 12:01 UTC by ahalberkamp

Remove travis and apply Github action for build.

2021-09-17 16:31 UTC, lojzatran requested changes

2021-09-17 16:31 UTC, lojzatran commented on README.md
> + executes it`s tests.
```suggestion
 executes its tests. 
```

2021-09-18 13:55 UTC, ahalberkamp commented on src/test/integration/java/com/commercetools/payment/handler/CommercetoolsGetPaymentsControllerIT.java
> +        super.setupBeforeAll();
without this change the test was failing in the git-action

2021-09-20 07:10 UTC, ahalberkamp commented on package-lock.json
> +  "lockfileVersion": 1
9b1ace6

2021-09-20 07:24 UTC, lojzatran commented on src/test/integration/java/com/commercetools/payment/handler/CommercetoolsGetPaymentsControllerIT.java
> +        super.setupBeforeAll();
That's weird that changing from travis to github actions you have to change the tests too, but ok.

2021-09-20 07:24 UTC, lojzatran approved these changes

2021-09-20 07:47 UTC, merged